### ISSUE TITLE
 No such file or directory: 'transfer_data/smpl_joint_regressor.npy'

### ISSUE THREAD

**Issue by FeiiYin** [oneThousand1000/Portrait3D#1]
Thanks for your impressive work! When I try to re-implment the work. It raise the error of 
```
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_data/smpl_joint_regressor.npy'
```
in   
```
File "Portrait3D/3DPortraitGAN_pyramid/training/aligned_smpl.py", line 26, in __init__
    np.load('transfer_data/smpl_joint_regressor.npy')).float().cuda().contiguous()
```
Can u provide some hint of where to download the file? Thanks!

**Comment by oneThousand1000** [comment]
Sorry for the missing file!
You can download it here: https://github.com/oneThousand1000/3DPortraitGAN/blob/main/3DPortraitGAN/transfer_data/smpl_joint_regressor.npy

I will upload it to this project soon.

**Comment by FeiiYin** [comment]
Thanks!!! Thanks for your so prompt response! U r the accademic Usain Bolt.
