### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Biggaoga** [oneThousand1000/Portrait3D#11]
Hi, thanks for your greate work, but I encounter an issue when running data_processing code, command i use is following:
`python preprocess_img_for_inversion.py --test_data_dir=/data/Portrait3D/test_data `, and it got a traceback:
```
Load checkpoint from demo_checkpoint.pth.tar
/data2/facescape/Portrait3D/data_processing/main/../common/utils/human_model_files/smpl/VPOSER_CKPT
Traceback (most recent call last):
  File "extract_camera_parameter.py", line 145, in <module>
    model = get_model(vertex_num, joint_num, 'test')
  File "/data2/facescape/Portrait3D/data_processing/demo/../main/model.py", line 624, in get_model
    vposer = Vposer()
  File "/data2/facescape/Portrait3D/data_processing/main/../common/nets/module.py", line 141, in __init__
    self.vposer, _ = load_vposer(osp.join(cfg.human_model_path, 'smpl', 'VPOSER_CKPT'), vp_model='snapshot')
  File "/home/gaoyujie/miniconda3/envs/portrait3d_data/lib/python3.8/site-packages/human_body_prior/tools/model_loader.py", line 56, in load_vposer
    ps, trained_model_fname = expid2model(expr_dir)
  File "/home/gaoyujie/miniconda3/envs/portrait3d_data/lib/python3.8/site-packages/human_body_prior/tools/model_loader.py", line 31, in expid2model
    best_model_fname = sorted(glob.glob(os.path.join(expr_dir, 'snapshots', '*.pt')), key=os.path.getmtime)[-1]
IndexError: list index out of range
```
it seems that I lack snapshots in `data_processing/common/utils/human_model_files/smpl/VPOSER_CKPT` this dir?

**Comment by oneThousand1000** [comment]
Yes, please check whether you meet all requirements in the readme:
![image](https://github.com/user-attachments/assets/40e977c3-af8f-494c-99f4-6b3177b63a7d)

**Comment by Biggaoga** [comment]
> Yes, please check whether you meet all requirements in the readme: ![image](https://private-user-images.githubusercontent.com/32099648/383112619-40e977c3-af8f-494c-99f4-6b3177b63a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDY4MDcsIm5iZiI6MTczMDgwNjUwNywicGF0aCI6Ii8zMjA5OTY0OC8zODMxMTI2MTktNDBlOTc3YzMtYWY4Zi00OTRjLTk5ZjQtNmIzMTc3YjYzYTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDExMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzY3NWM3NWMwNzA1YTE1MTgzZDUwMmM1OWZlZTcxMDdkZmE1ZDNlMjMyNjcwOTM2MzM0NmIwNDYwOTM2OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xXsiqSjvbuitPaVqjkedUtWKMRz892Js8NheeNfvFJs)

I see, thanks for your reply!
