### ISSUE TITLE
How can the trained model be imported into 3D software?

### ISSUE THREAD

**Issue by codek0520** [oneThousand1000/Portrait3D#2]

**Comment by oneThousand1000** [comment]
hi! We generate a `.mrc` file in our final results for geometry visualization. You can refer to https://github.com/NVlabs/eg3d#generating-media for the visualization instruction of the mrc file, you can also use it to extract a .obj file.

However, our resulting geometry is still not good enough. We also have not implement texture extraction. We will consider these issues as future work.

**Comment by codek0520** [comment]
OK, thanks for your reply
