### ISSUE TITLE
Can't install libosmesa6 libosmesa6-dev on centons

### ISSUE THREAD

**Issue by icekeg** [oneThousand1000/Portrait3D#3]

**Comment by icekeg** [comment]
As title said, I can't install libosmesa6 libosmesa6-dev on centons, Is there any solution?

**Comment by oneThousand1000** [comment]
Hi, I haven't tested it on centos. You could find detailed Osmesa installation instruction here: https://pyrender.readthedocs.io/en/latest/install/index.html

**Comment by icekeg** [comment]
thank you, I'll try it.

**Comment by icekeg** [comment]
I installed libXext libSM libXrender and fixed it.
